// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnoqknkqvygbrbzgnswn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNub3FrbmtxdnlnYnJiemduc3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MzAzNDUsImV4cCI6MjA1NjAwNjM0NX0.fsfIIs62936D7nYPc_MQ1NCEYXHZASpEXBELTegmkMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);